copyright = "2017-2026 © Debug客栈, by @debuginn."
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en"
timeZone = "Asia/Shanghai"
timeout = "120s"
title = "Debug客栈"
theme = "gallery"

[params]
defaultTheme = "dark"
description = "您好，我是 Meng小羽，非标准程序猿，爱好 Coding、Music and Photography。"
title = "摄影展"
[params.author]
email = "idebuginn@gmail.com"
name = "Meng小羽"
[params.socialIcons]
email = "mailto:idebuginn@gmail.com"
github = "https://github.com/debuginn"
website = "https://debuginn.com"

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML"]

[imaging]
quality = 100
resampleFilter = "CatmullRom"
[imaging.exif]
disableDate = false
disableLatLong = true
includeFields = "ImageDescription|Orientation"

[module]
[module.hugoVersion]
min = "0.121.2"

[menu]
[[menu.footer]]
name = "GitHub"
url = "https://github.com/nicokaiser/hugo-theme-gallery/"
weight = 3

[services]
[services.rss]
limit = 100
